### ISSUE TITLE
Add 10 java codes in 1star to 2star directory 

### ISSUE THREAD

**Issue by vickyrules** [vickyrules/CodeChef_SelfLearning#1]
Add all or at least 10 remaining solutions in  (⭐ to ⭐⭐) to their respective markdown files.

<a href = "https://github.com/vickyrules/CodeChef_SelfLearning/tree/main/%E2%AD%90%20to%20%E2%AD%90%E2%AD%90">Folder link</a>

**Comment by vickyrules** [comment]
#Note: Please ask to assign before working on the issues

**Comment by Urmilasc** [comment]
Hello , I want to contribute in this , so can you please assign to me?

**Comment by vickyrules** [comment]
> Hello , I want to contribute in this , so can you please assign to me?
@Urmilasc  this one is assigned please ask for other issues.

**Comment by vickyrules** [comment]
@Urmilasc  any update?

**Comment by Urmilasc** [comment]
Sorry, I can't able to complete this , please assign this to someone else , extremely  sorry.
