### ISSUE TITLE
add any 3 solutions in 2 stars to 3 stars directory using java.

### ISSUE THREAD

**Issue by vickyrules** [vickyrules/CodeChef_SelfLearning#10]
add any 3 solutions in 2 stars to 3 stars directory using java.
[link](https://github.com/vickyrules/CodeChef_SelfLearning/tree/main/%E2%AD%90%E2%AD%90%20to%20%E2%AD%90%E2%AD%90%E2%AD%90)

**Comment by Rakteem007** [comment]
can you assign this to me

**Comment by Rakteem007** [comment]
i have solved the issue

**Comment by Rakteem007** [comment]
I solved the conflicts and created a fresh PR. I hope this will do.
