### ISSUE TITLE
Add problem description of the remaining questions (atleast 5)

### ISSUE THREAD

**Issue by vickyrules** [vickyrules/CodeChef_SelfLearning#11]
Add problems descriptions of remaining questions (at least 5)

How to add:
* click on the link provided in the readme 
* and go to the respective question.
* open inspect and copy the whole div with id = (problem_statment)
* and paste it into the markdown file.

[sample file](https://github.com/vickyrules/CodeChef_SelfLearning/blob/main/%E2%AD%90%20to%20%E2%AD%90%E2%AD%90/Arrays/SUBTASK.md)

***Don't add the code solutions.

**Comment by JatinSingh08** [comment]
Hey @vickyrules , Please assign this to me. I would love to contribute.

**Comment by vickyrules** [comment]
@JatinSingh08 Do it as soon as possible:

**Comment by vickyrules** [comment]
@JatinSingh08 any update?

**Comment by Vikasffic** [comment]
@vickyrules want to contribute, assign this to me please?

**Comment by Vikasffic** [comment]
> @vickyrules want to contribute, assign this to me please?

Do for 3stars to 4 stars

**Comment by ZianiImane** [comment]
I'd like to contribute to this issue, please.

**Comment by vickyrules** [comment]
> I'd like to contribute to this issue, please.

@ZianiImane sure.

**Comment by Rakteem007** [comment]
can I contribute?
