### ISSUE TITLE
mistake in saving md file

### ISSUE THREAD

**Issue by pavankumarraju13** [vickyrules/CodeChef_SelfLearning#13]
The .md file under the binary search file in the 2 to 3 stars folder is incorrectly saved

**Comment by pavankumarraju13** [comment]
@vickyrules can i correct the issue

**Comment by vickyrules** [comment]
> @vickyrules can i correct the issue

what and where is the mistake?

**Comment by pavankumarraju13** [comment]
> > @vickyrules can i correct the issue
> 
> what and where is the mistake?

**Comment by pavankumarraju13** [comment]
saved with ','

**Comment by vickyrules** [comment]
> saved with ','

no need to create a separate issue for that.
