### ISSUE TITLE
ADD Link to the problem in their respective markdown file  (at least 15).

### ISSUE THREAD

**Issue by vickyrules** [vickyrules/CodeChef_SelfLearning#27]
ADD the codechef online IDE  Links of the problems in their respective markdown file (at the bottom).

Do at least 15 to get approved.

**Comment by Rakteem007** [comment]
> ADD the codechef online IDE Links of the problem in their respective markdown file (at the bottom).
> 
> Do at least 15 to get approved.

do you mean the IDE of codechef? @vickyrules

**Comment by vickyrules** [comment]
> > ADD the codechef online IDE Links of the problem in their respective markdown file (at the bottom).
> > Do at least 15 to get approved.
> 
> do you mean the IDE of codechef? @vickyrules

Just add the link of each problem at the top of the   markdown file.

**Comment by Rakteem007** [comment]
okk  can you please assign this to me
