### ISSUE TITLE
Add all  solutions using java in 0 _to ⭐ (in their respective markdown files. )

### ISSUE THREAD

**Issue by vickyrules** [vickyrules/CodeChef_SelfLearning#4]
Add all solutions in java in   0_ to ⭐ to their respective markdown files.

[Folder link](https://github.com/vickyrules/CodeChef_SelfLearning/tree/main/_%20to%201%20%E2%AD%90/Basic%20Programming)

**Comment by vickyrules** [comment]
# Note: Please ask to assign before working on the issues

**Comment by vickyrules** [comment]
@Urmilasc Want to work for this one?

**Comment by Urmilasc** [comment]
How many solution code we have to provide?

**Comment by vickyrules** [comment]
> How many solution code we have to provide?

Do all in any one language (java or python ) in 0 star to 1 star folder.

**Comment by MinalGhate** [comment]
Hello sir I would like to work on this issue
