### ISSUE TITLE
ADD SOLUTIONS USING JAVA-[STRINGS]

### ISSUE THREAD

**Issue by vickyrules** [vickyrules/CodeChef_SelfLearning#45]
***ADD YOUR SOLUTIONS IN THE FOLLOWING FOLDER:***
[STRINGS](https://github.com/vickyrules/CodeChef_SelfLearning/tree/main/%E2%AD%90%20to%20%E2%AD%90%E2%AD%90/Strings)

*** Add Solutions to the following Problems:
[EQUINQX](https://www.codechef.com/submit/EQUINOX)
[ERROR](https://www.codechef.com/submit/ERROR)
[HIRETEST](https://www.codechef.com/submit/HIRETEST)
[MAGDOORS](https://www.codechef.com/submit/MAGDOORS)
[PASSWD](https://www.codechef.com/submit/PASSWD)
[SNAAKPROC](https://www.codechef.com/submit/SNAKPROC)

**NOTE**
*  Please add relevant comments to your code.
*  Plagiarism can't be tolerated.
*  Add valid and meaningful commit messages
*  Fill PR details carefully.

**Comment by Amit12234** [comment]
please assign me this issue

**Comment by vickyrules** [comment]
> please assign me this issue

@Amit12234 sure:

Don't forget to ⭐the repo.
