### ISSUE TITLE
Add solutions using Python-[STRINGS]

### ISSUE THREAD

**Issue by vickyrules** [vickyrules/CodeChef_SelfLearning#46]
***ADD YOUR SOLUTIONS IN THE FOLLOWING FOLDER:***
[STRINGS](https://github.com/vickyrules/CodeChef_SelfLearning/tree/main/%E2%AD%90%20to%20%E2%AD%90%E2%AD%90/Strings)

*** Add Solutions to the following Problems:

[ERROR](https://www.codechef.com/submit/ERROR)
[MAGDOORS](https://www.codechef.com/submit/MAGDOORS)
[SNAAKPROC](https://www.codechef.com/submit/SNAKPROC)

**NOTE**
*  Please add relevant comments to your code.
*  Plagiarism can't be tolerated.
*  Add valid and meaningful commit messages
*  Fill PR details carefully.

**Comment by Suveksha25** [comment]
I would like to work on this. Can you assign it to me

**Comment by vickyrules** [comment]
@Suveksha25 sure.

Don't forget to ⭐ the repo.

**Comment by Suveksha25** [comment]
@vickyrules I have given a PR

**Comment by vickyrules** [comment]
> @vickyrules I have given a PR

@Suveksha25 Next Time, Please mention the issue number in your PR that you have solved.
