### ISSUE TITLE
ADD SOLUTION USING JAVA-[BASICS] (2Stars - 3 Stars)

### ISSUE THREAD

**Issue by vickyrules** [vickyrules/CodeChef_SelfLearning#47]
***ADD YOUR SOLUTIONS IN THE FOLLOWING FOLDER:***
[BASIC_CONCEPTS](https://github.com/vickyrules/CodeChef_SelfLearning/tree/main/%E2%AD%90%E2%AD%90%20to%20%E2%AD%90%E2%AD%90%E2%AD%90/Basics%20Concepts)

*** Add Solutions to the following Problems:
[INDIPERM](https://www.codechef.com/submit/INDIPERM)
[MAKEDIV](https://www.codechef.com/submit/MAKEDIV3)
[MINIPIZZAS](https://www.codechef.com/submit/MINPIZZAS)
[NFS](https://www.codechef.com/submit/NFS)

**NOTE**
*  Please add relevant comments to your code.
*  Plagiarism can't be tolerated.
*  Add valid and meaningful commit messages
*  Fill PR details carefully.

**Comment by Amit12234** [comment]
please assign me this

**Comment by vickyrules** [comment]
@Amit12234 sure:

Don't forget to ⭐the repo.
