### ISSUE TITLE
Add all  solutions in python in 0 _to ⭐(in  their respective markdown files).  

### ISSUE THREAD

**Issue by vickyrules** [vickyrules/CodeChef_SelfLearning#5]
Add all solutions using python in   0_ to ⭐

[Folder link](https://github.com/vickyrules/CodeChef_SelfLearning/tree/main/_%20to%201%20%E2%AD%90/Basic%20Programming)

**Comment by vickyrules** [comment]
# Note: Please ask to assign before working on the issues

**Comment by vividxz** [comment]
I would like to work on this, please assign this to me.

**Comment by vickyrules** [comment]
> I would like to work on this, please assign this to me.

@vividxz  Sure

**Comment by vickyrules** [comment]
@vividxz  any update?

**Comment by Vikasffic** [comment]
@vickyrules want to work. Please assign this to me.

**Comment by vickyrules** [comment]
@vividxz are you doing or I will assign it to @Vikasffic
