### ISSUE TITLE
PART-2 -->Add solution using JAVA -[Binary Search] -(2stars to 3 stars)

### ISSUE THREAD

**Issue by vickyrules** [vickyrules/CodeChef_SelfLearning#57]
#Description:
ADD SOLUTIONS TO THE  PROBLEMS LISTED BELOW USING JAVA

***ADD YOUR SOLUTIONS IN THE FOLLOWING FOLDER:***
[BINARY SEARCH](https://github.com/vickyrules/CodeChef_SelfLearning/blob/main/%E2%AD%90%E2%AD%90%20to%20%E2%AD%90%E2%AD%90%E2%AD%90/Binary%20Search/)

*** Add Solutions to the following Problems:

* [SNAKEEAT](https://www.codechef.com/submit/SNAKEEAT)
* [SNTEMPLE](https://www.codechef.com/submit/SNTEMPLE)
*  [SQUIRREL](https://www.codechef.com/submit/SQUIRREL)
* [STACKS](https://www.codechef.com/submit/STACKS)

**NOTE**
*  Please add relevant comments to your code.
*  Plagiarism can't be tolerated.
*  Add valid and meaningful commit messages
*  Fill  PRs details carefully and mention the issue number that you have solved.

**Comment by Amit12234** [comment]
please assign me this
