### ISSUE TITLE
Add any 2 solutions using java in 3stars to 4stars. 

### ISSUE THREAD

**Issue by vickyrules** [vickyrules/CodeChef_SelfLearning#6]
Add any 2 solutions using java in 3stars to 4stars. 
[folder link](https://github.com/vickyrules/CodeChef_SelfLearning/tree/main/%E2%AD%90%E2%AD%90%E2%AD%90%20to%20%E2%AD%90%E2%AD%90%E2%AD%90%E2%AD%90)

**Comment by Rakteem007** [comment]
can I try to solve this issue?

**Comment by vickyrules** [comment]
> can I try to solve this issue?

@Rakteem007 go for it.
