### ISSUE TITLE
Add 2 solutions using python in 3 stars to 4 stars

### ISSUE THREAD

**Issue by vickyrules** [vickyrules/CodeChef_SelfLearning#7]
Add any 2 solutions using python in 3 stars to 4 stars
[directory](https://github.com/vickyrules/CodeChef_SelfLearning/tree/main/%E2%AD%90%E2%AD%90%E2%AD%90%20to%20%E2%AD%90%E2%AD%90%E2%AD%90%E2%AD%90)

**Comment by Vikasffic** [comment]
@vickyrules please assign this. Want to conntribute.
