### ISSUE TITLE
Add  at least 5 remaining solutions  using pythhon in  (⭐ to ⭐⭐)  their respective markdown files.

### ISSUE THREAD

**Issue by vickyrules** [vickyrules/CodeChef_SelfLearning#8]
Add all or at least 5 remaining solutions in  (⭐ to ⭐⭐) .

<a href = "https://github.com/vickyrules/CodeChef_SelfLearning/tree/main/%E2%AD%90%20to%20%E2%AD%90%E2%AD%90">Folder link</a>

**Comment by Rakteem007** [comment]
can i work on this ?

**Comment by vickyrules** [comment]
@

> can I work on this?

@Rakteem007 Be sure to add the problem description if not been added already.

**Comment by Rakteem007** [comment]
> @
> 
> > can I work on this?
> 
> @Rakteem007 Be sure to add the problem description if not been added already.

ok Sir.
