### ISSUE TITLE
add any 3 solutions in 2 stars to 3 stars directory using python.

### ISSUE THREAD

**Issue by vickyrules** [vickyrules/CodeChef_SelfLearning#9]
add any 3 solutions in 2 stars to 3 stars directory using python.
[link](https://github.com/vickyrules/CodeChef_SelfLearning/tree/main/%E2%AD%90%E2%AD%90%20to%20%E2%AD%90%E2%AD%90%E2%AD%90)

**Comment by pavankumarraju13** [comment]
hey @vickyrules can you assign this to me

**Comment by pavankumarraju13** [comment]
@vickyrules can you elaborate a bit what to be done ?

**Comment by vickyrules** [comment]
@pavankumarraju13 
add solutions of the problems in the respective markdown file on any topic

**Comment by vickyrules** [comment]
@pavankumarraju13 any update?

**Comment by pavankumarraju13** [comment]
@vickyrules  i will update within hour

**Comment by Vikasffic** [comment]
@vickyrules  want to work on this issue.
